#  Various Data Types in Python





## 1 Numeric (int , float , complex)

In [2]:
1+1

2

In [3]:
4*5


20

In [4]:
2/10


0.2

In [40]:
a=12.6
b=10
c=2j+5
print(a,b,c)

12.6 10 (5+2j)


In [5]:
10*"seema"

'seemaseemaseemaseemaseemaseemaseemaseemaseemaseema'

##  type(x) is used to check data type


In [6]:
type(1)

int

In [8]:
type("seema")

str

## 2 String str
## there are mne inbuilt function for string 
## variable name . press tab 

In [38]:
"Hello" # use single quotes
name="seema"
print(name.isalnum())# char and number
print(name.isalpha()) # aplhabetic
print(name.isdigit()) # digits
print(name.istitle()) # title word
print(name.isupper()) 
print(name.islower())
print(name.isspace())


True
True
False
False
False
True
False


In [10]:
'Hello' # use double quotes

'Hello'

## 3 Sequence types: list, tuple, range

## list

In [42]:
#list 
# data structure 
# mutable->changeable
# ordered sequence of elements
# Each value in list called ->Item
# values inside [] sqaure  brackets 
type([])

list

In [51]:
list1=[] # inbuild function list() to create empty list
type(list1)

list

## append()


In [ ]:
list.append("Rohit") # append()->add more item in last/end
print(list)

## indexing()

In [60]:
list=["seema",18,"wheat",8,"Good"] # comma separated values
print(len(list)) # len()->inbuilt ->count of item
print(list)

# Indexing in list start from 0
print(list[2])
#indexing can be done from range
print(list[:]) # :->pick all item
print(list[1:]) # from 1 to all
print(list[1:4]) # from start to end-1  --> 1 to 3

5
['seema', 18, 'wheat', 8, 'Good']
['seema', 18, 'wheat', 8, 'Good', 'Rohit']
wheat
['seema', 18, 'wheat', 8, 'Good', 'Rohit']
[18, 'wheat', 8, 'Good', 'Rohit']
[18, 'wheat', 8]


## insert()

In [62]:
# insert at specific index/order
list.insert(0,"sushila")
print(list)

['sushila', 'seema', 18, 'wheat', 8, 'Good', 'Rohit']


## extend()

In [66]:
mylist=[1,'seema']
mylist.extend(["rohit",19]) # add more than one element and append at a time you insert one element
print(mylist)
mylist.extend(["maa",[1,2,3]])
print(mylist)

[1, 'seema', 'rohit', 19]
[1, 'seema', 'rohit', 19, 'maa', [1, 2, 3]]


## various operations that we can perform in list

In [71]:
# pop() Method --->reomve last element
mylist=['sushila', 'seema', 18, 'wheat', 8, 'Good', 'Rohit']
print(mylist)
mylist.pop()
print(mylist)
mylist.pop(1)   #-->remove element at index 0
print(mylist)

['sushila', 'seema', 18, 'wheat', 8, 'Good', 'Rohit']
['sushila', 'seema', 18, 'wheat', 8, 'Good']
['sushila', 18, 'wheat', 8, 'Good']


In [74]:
# count() count  of ans element in list
mylist.count("Good")

1

In [78]:
# index(element ,start,end)  -->return first occurence of element b/w start to end
lst=['1',2,1,'3','4',5,1 ,6,7,8]
print(lst.index('3')) #-->bydefault start =0 and end is last index 

print(lst.index(1,2,9))
print(lst.index(1,3,9))

3
2
6


In [81]:
# min() to find mini
# max() to find max
list1=['1','2','3','4']
print(min(list1))
print(max(list1))

1
4


## Binary types: bytes, bytearray, memoryview.

##  4 Mapping data type: dict

## 5  Boolean type: bool 


In [32]:
#  two values 1: true 2: false
type(True)
type(False)

bool

## 6 Set Types:	set, frozenset

# Set

In [ ]:
# unordered collection of data type
# mutable->changeable
# no duplicate elemnt

In [83]:
sett=set()
print(sett)
type(sett)

set()


set

In [85]:
# set creation {} are use element inside it
sett={"seema","Rohit",1,2,"seema"}; # remove duplicate and unorder
print(sett)

{'Rohit', 2, 'seema', 1}


In [ ]:
#Indexing -->index()

In [86]:
print(sett[1])  # does not support indexing

TypeError: 'set' object is not subscriptable

In [89]:
# add()->used to add elemnt in set
sett.add("Maa")
print(sett)
set1={1,2,3,4,5,6}
set2={1,3,4,7,8,10}
print(set1.union(set2)) # union -->not update in original set1 
print(set1.intersection(set2)) # intersection not update in original set1
print(set1.difference(set2))  # difference not update in original set1

{1, 2, 'Maa', 'seema', 'Rohit'}
{1, 2, 3, 4, 5, 6, 7, 8, 10}
{1, 3, 4}
{2, 5, 6}


##  Dictionary

In [90]:
# dic  -->key -value pair
my_dic={"car":"swift desire","Truck":"dadanimnath","Bike":"splender"}
print(my_dic);
print(type(my_dic))

{'car': 'swift desire', 'Truck': 'dadanimnath', 'Bike': 'splender'}
<class 'dict'>


In [91]:
# how to access value using key
print(my_dic['car'])

swift desire


In [99]:
for x in my_dic:
    print(x)
for x in my_dic.values():
    print(x)
for x in my_dic.items():
   print(x)
my_dic["car"]="i10" # overwritten
print(my_dic)

car
Truck
Bike
swift desire
dadanimnath
splender
('car', 'swift desire')
('Truck', 'dadanimnath')
('Bike', 'splender')
{'car': 'i10', 'Truck': 'dadanimnath', 'Bike': 'splender'}


In [103]:
# Nested dictionary
car1_model={"swift":1980}
car2_model={"breja":2000}
car3_model={"thar":2023}
mydic={'car1':car1_model,'car2':car2_model,'car3':car3_model}
print(mydic['car1']["swift"])



1980


# tuple

In [104]:
# use () braces 
# you can not change tuple
# indexing is valid
mytuple=(1,2,3,4,5,6)
print(mytuple)
print(mytuple[3])
# does not support  item assigment like mytuple[3]="seema"
# you can change tuple whole tuple
# index()
# count()

(1, 2, 3, 4, 5, 6)
4


## 7 Binary Types:	bytes, bytearray, memoryview

## 8 None Type:	NoneType

## Variable assignment 

In [11]:
#syntax
# var_name=value
a=10

In [12]:
type(a)

int

In [13]:
a="seema"

In [14]:
type(a)

str

In [15]:
# Print() function is used to print anything
print(a)
print("seema")
print(40)
print(78.9)
print(True)

seema
seema
40
78.9
True


In [ ]:
## various ways of printing

In [20]:
first_name='seema'
last_name='sangwan'


In [21]:
print("my first name is {first} and last name is {last}".format(first=first_name,last=last_name))

my first name is seema and last name issangwan


In [22]:
print("my first name is {} and my last name is {} ".format(first_name,last_name))

my first name is seema and my last name is sangwan 


In [23]:
print("my first name is {first} and last name is {last}".format(last=last_name,first=first_name))

my first name is seema and last name is sangwan


In [25]:
# len() give length of string
len("seema")
a="sangwan"
len(a)

7

In [26]:
type(1.0)

float

In [27]:
# List is collection of data need not to be of same type
#can have differemt data type like int , float,bool, string
# syntax a=[data]
type(['seema',18,'IGDTUW' ,3,2025])

list

## Logical operators

In [41]:
## and ,or
## and all true->true
## or  atleast one true->true
print(True and True) ##true
print(True and False) ##false
print(False and True)  ##false
print(False and False)  ##false
print(True or True)   #true
print(True or False)  #true
print(False or True)   #true
print(False or False)   ##false

True
False
False
False
True
True
True
False


## Sets


##  Numpy Library

In [ ]:
# NumPy is a general purpose array processing package . 
# use to create multi dimesional array and inbuilt functiom

In [3]:
 # Initailly lets import numpy
import numpy as np

In [109]:
mylst=[1,2,3,4,5]
arr=np.array(mylst) # array()--->inbuilt function to create
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [110]:
arr  # one d array


array([1, 2, 3, 4, 5])

In [111]:
arr.shape # now of row and col


(5,)

In [5]:
# multi dimesional array
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[9,10,11,12]
arr=np.array([lst1,lst2,lst3])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr.shape

(3, 4)

In [7]:

arr.reshape(4,3)



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [ ]:
Indexing 

In [9]:
# 1D array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[3]


4

In [10]:
# 2d Indxing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#indexing in 2d array
# lhs->row no.
# rhs->column no.
# :,: access all row and column
#:, c: access all column c or after c
print(  arr[:,:])
print(arr[:,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]


In [3]:
import numpy as nm
list =[1,2,3,4,5]
arr=nm.array(list)
print(arr)
listt=[6,7,8,9,10]
arrw=nm.array([list,listt])
print(arrw)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


arrw.reshape(5,2)


# Indexing in array (learn how to reteriew data from array)
# o based indexing 

In [7]:
array=nm.array([1,2,3,4,5,6,7,8]);
for i in array:
    print(i)

1
2
3
4
5
6
7
8


In [9]:
i=0 
while(i<len(array)):
    print(array[i])
    i=i+1
  

1
2
3
4
5
6
7
8


In [10]:
print(array[4])

5


#  indxing in 2d array

In [11]:
array=nm.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in array:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [13]:
for i in array:
    print (i)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [14]:
print(array[1][2])

8


In [22]:
pip install numpy




SyntaxError: invalid syntax (3155855143.py, line 1)

In [23]:
import numpy as nm

In [25]:
array1=nm.arange(0,10)
print(array1)
array2=nm.arange(0,10,2)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [29]:
array3=nm.linspace(0,10,5)
print(array3)
array4=nm.linspace(1,10,5)
print(array4)

[ 0.   2.5  5.   7.5 10. ]
[ 1.    3.25  5.5   7.75 10.  ]
