In [4]:
## copy and broadcasting
import numpy as nm



In [5]:
arr=nm.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr2=arr
arr2[3:]=100
print(arr2)
print(arr)
## when we make change to copied array then it reflect in original array 
## means arr1=arr copy by  refernece

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3 100 100 100 100 100 100 100]
[  1   2   3 100 100 100 100 100 100 100]


In [5]:
## when we use copy function to  copy array then there is no change reflect in orginal arra
arr1=nm.array([1,2,3,4,5,6,7,8])
print(arr1)
arr3=arr1.copy()
arr3[3:]=10000
print(arr3)
print(arr1)

[1 2 3 4 5 6 7 8]
[    1     2     3 10000 10000 10000 10000 10000]
[1 2 3 4 5 6 7 8]


In [ ]:
## copy function make new array 
## not share same memory location

In [6]:
## some condition very useful in Exploratory Data Analysis
val=2
arr<2  ## check each and every element < 2 or not 


array([ True, False, False, False, False, False, False, False, False,
       False])

In [10]:
print(arr*2)

[  2   4   6 200 200 200 200 200 200 200]


In [11]:
## if i want exact element which are less than 
arr[arr<300]

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [12]:
## nm.ones(4) create an array which is basically replaced 1
nm.ones(4)

array([1., 1., 1., 1.])

In [14]:
nm.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
## random distribution  rand(no. of row , no. of columns)
nm.random.rand(3,3) ## three row and three column between 0 to 1

array([[0.70763999, 0.95732714, 0.93270384],
       [0.4687889 , 0.1514779 , 0.66563894],
       [0.6592525 , 0.86519263, 0.22786474]])

In [17]:
### randn()=> it will generate random standard normal distribution
newarr=nm.random.randn(3,3)

In [18]:
newarr

array([[-1.35044905, -0.68515251, -0.10594394],
       [ 1.59065267, -0.1270388 ,  0.12678458],
       [-1.44118017,  0.34080798, -0.40108843]])

In [19]:
## randint(start,stop,n) it will select n number between start and stop
nm.random.randint(0,5,4)

array([1, 1, 4, 0])

In [ ]:
## random_sample(a,b) also generate 0 to 1 a->rows b->columns